"""Self-contained local dashboard for the read-only stream watcher."""

from __future__ import annotations


PAGE = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Driftline Live Watch</title>
<style>
:root{--ink:#edf7f4;--muted:#91aaa5;--panel:#102a2bde;--line:#28504d;--sea:#62e0c0;--gold:#f0c46b;--red:#ff8177;--bg:#061718}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% -10%,#194c48 0,transparent 35%),linear-gradient(145deg,#061718,#091e20 58%,#071414);color:var(--ink);font:15px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;min-height:100vh}
.shell{max-width:1320px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:22px}.brand{display:flex;gap:14px;align-items:center}.mark{width:50px;height:50px;border:1px solid #4c8179;border-radius:15px;display:grid;place-items:center;background:#0d302f;font-size:25px;box-shadow:0 12px 35px #0008}.eyebrow{color:var(--sea);letter-spacing:.17em;font-size:11px;font-weight:750}.brand h1{margin:2px 0 0;font-size:25px;letter-spacing:-.03em}.pulse{display:flex;align-items:center;gap:9px;color:var(--sea);font-weight:700}.dot{width:10px;height:10px;border-radius:50%;background:var(--sea);box-shadow:0 0 0 0 #62e0c088;animation:pulse 1.8s infinite}@keyframes pulse{70%{box-shadow:0 0 0 10px #62e0c000}}
.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px}.card{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:18px;box-shadow:0 18px 50px #0004;backdrop-filter:blur(12px)}.metric{grid-column:span 3}.metric .label,.section-title{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.12em;font-weight:750}.metric .value{font-size:28px;font-weight:780;margin-top:8px;letter-spacing:-.04em}.metric .sub{color:var(--muted);font-size:12px;margin-top:2px}.scanner{grid-column:span 8}.events{grid-column:span 4}.safety{grid-column:span 12;display:flex;justify-content:space-between;align-items:center;gap:16px}.section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.table-wrap{overflow:auto;max-height:480px}table{width:100%;border-collapse:collapse;white-space:nowrap}th{color:var(--muted);font-size:11px;text-align:right;padding:9px 8px;border-bottom:1px solid var(--line);position:sticky;top:0;background:#102a2b}th:first-child,td:first-child{text-align:left}td{text-align:right;padding:11px 8px;border-bottom:1px solid #1c3b39;font-variant-numeric:tabular-nums}.sym{font-weight:800;color:#fff}.up{color:var(--sea)}.down{color:var(--red)}.tag{display:inline-block;padding:3px 8px;border-radius:99px;background:#173c39;color:#b9d8d1;font-size:10px;letter-spacing:.06em}.stream{height:442px;overflow:auto}.event{border-left:2px solid var(--sea);padding:2px 0 14px 12px;margin:0 0 4px}.event.alert{border-color:var(--gold)}.event strong{font-size:13px}.event p{margin:3px 0;color:var(--muted);font-size:12px}.event time{color:#688681;font-size:10px}.empty{color:var(--muted);padding:35px 8px;text-align:center}.safe{display:flex;align-items:center;gap:12px}.shield{font-size:28px}.safe strong{display:block}.safe span{color:var(--muted);font-size:12px}button{border:1px solid #5b8e85;background:#143b38;color:white;border-radius:12px;padding:10px 14px;font-weight:750;cursor:pointer}button:hover{background:#1b4b47}button:disabled{opacity:.55}.stamp{color:var(--muted);font-size:12px}.error{color:var(--red)}
@media(max-width:850px){.shell{padding:18px}.metric{grid-column:span 6}.scanner,.events{grid-column:span 12}.top,.safety{align-items:flex-start;flex-direction:column}.stream{height:260px}}@media(max-width:480px){.metric{grid-column:span 12}.brand h1{font-size:21px}}
</style>
</head>
<body><main class="shell">
<header class="top"><div class="brand"><div class="mark">◉</div><div><div class="eyebrow">DRIFTLINE</div><h1>Live Market Watch</h1></div></div><div id="connection" class="pulse"><i class="dot"></i><span>Connecting…</span></div></header>
<section class="grid">
<article class="card metric"><div class="label">Symbols watched</div><div class="value" id="symbols">—</div><div class="sub">dynamic universe</div></article>
<article class="card metric"><div class="label">Market messages</div><div class="value" id="messages">—</div><div class="sub">since this launch</div></article>
<article class="card metric"><div class="label">Trades inspected</div><div class="value" id="trades">—</div><div class="sub">live IEX events</div></article>
<article class="card metric"><div class="label">Alerts sent</div><div class="value" id="alerts">—</div><div class="sub">early heads-ups</div></article>
<article class="card scanner"><div class="section-head"><div><div class="section-title">Live scanner</div><div class="stamp" id="scanStamp">Waiting for market data…</div></div><span class="tag">AUTO REFRESH</span></div><div class="table-wrap"><table><thead><tr><th>Symbol</th><th>Last</th><th>Bid</th><th>Ask</th><th>Day</th><th>15 sec</th><th>60 sec volume</th><th>Spread</th></tr></thead><tbody id="rows"></tbody></table></div></article>
<article class="card events"><div class="section-head"><div><div class="section-title">Watcher activity</div><div class="stamp">What the program is doing</div></div></div><div class="stream" id="events"></div></article>
<article class="card safety"><div class="safe"><div class="shield">🛡️</div><div><strong>READ ONLY — PAPER TRAINING</strong><span>No real or paper order can be placed, changed, or canceled from this program.</span></div></div><button id="test">Send safe test alert</button></article>
</section></main>
<script>
const $=id=>document.getElementById(id), fmt=n=>Number(n||0).toLocaleString(), money=n=>Number(n||0).toFixed(Number(n)<10?4:2), pct=n=>{n=Number(n||0);return `<span class="${n>=0?'up':'down'}">${n>=0?'+':''}${n.toFixed(2)}%</span>`};
function age(iso){if(!iso)return 'No messages yet';let s=Math.max(0,Math.round((Date.now()-new Date(iso))/1000));return s<2?'just now':s<60?`${s}s ago`:`${Math.floor(s/60)}m ago`}
async function refresh(){try{let r=await fetch('/api/live',{cache:'no-store'}),d=await r.json(),h=d.health,c=$('connection');c.className=h.connected?'pulse':'pulse error';c.querySelector('span').textContent=h.connected?`Connected · ${h.feed.toUpperCase()} live feed`:'Disconnected · reconnecting';$('symbols').textContent=fmt(h.symbols);$('messages').textContent=fmt(h.message_count);$('trades').textContent=fmt(h.trade_count);$('alerts').textContent=fmt(h.alert_count);$('scanStamp').textContent=`Latest market message ${age(h.last_message_at)} · universe refreshed ${age(h.last_universe_refresh_at)}`;$('rows').innerHTML=d.symbols.length?d.symbols.map(s=>`<tr><td class="sym">${s.symbol}</td><td>$${money(s.last)}</td><td>$${money(s.bid)}</td><td>$${money(s.ask)}</td><td>${pct(s.day_move_pct)}</td><td>${pct(s.acceleration_pct)}</td><td>${fmt(s.volume_60s)}</td><td>${Number(s.spread_pct).toFixed(2)}%</td></tr>`).join(''):`<tr><td colspan="8" class="empty">Connected and waiting for live trades. Rows appear as the market moves.</td></tr>`;$('events').innerHTML=d.events.length?d.events.map(e=>`<div class="event ${e.kind==='alert'?'alert':''}"><strong>${e.title}</strong><p>${e.detail}</p><time>${new Date(e.timestamp).toLocaleTimeString()}</time></div>`).join(''):`<div class="empty">Startup activity will appear here.</div>`}catch(e){$('connection').className='pulse error';$('connection').querySelector('span').textContent='Dashboard reconnecting…'}}
$('test').onclick=async()=>{let b=$('test');b.disabled=true;b.textContent='Sending…';try{let r=await fetch('/api/test-alert',{method:'POST'}),d=await r.json();b.textContent=d.ok?'Test sent ✓':d.message||'Could not send'}catch(e){b.textContent='Could not send'}setTimeout(()=>{b.disabled=false;b.textContent='Send safe test alert'},4000);refresh()};refresh();setInterval(refresh,1500);
</script></body></html>'''


def dashboard_page() -> bytes:
    return PAGE.encode("utf-8")
